### PR TITLE
Initial commit to update supported version of WordPress

### PR DESCRIPTION
**Pull request by karmatosed**
#### What?

This bumps the version of WordPress to look to solve the readme file piece of #458.

### Additional

This will still need testing beyond this version and a new plugin version released once this happens.

### CODE REVIEW

**Comment by karmatosed** [comment]
Note, I also bumped the stable tag of the plugin in readme as this will need to be released. I am unaware is this happens as part of generation though so can remove if required.

I also couldn't find documentation on how version numbers were updated across plugin but happy to prepare something for that also.

**Comment by karmatosed** [comment]
Additionally I brought in an updated changlog file - not sure this is auto generated so can always iterate if that is case.

**Review by chanceaclark — COMMENTED** [review]
Hey @karmatosed thanks for testing and updating this. You can actually remove the changelog addition as we do that whenever we release a new version. Once that's done, I'll throw a ✅

**Comment by karmatosed** [comment]
Ok great, will work on that now.

**Review by chanceaclark — APPROVED** [review]
Thanks making the change earlier. I realized that we should probably just release after this PR is merged so I added the additional items needed to cut a release. Apologies for giving you a little bit of a run around here.

**Pull request merged**
