### PR TITLE
packaged version 4.23.0

### PR DESCRIPTION
**Pull request by MlKilderkin**
### Added
- In order to speed up the import process running import tasks in parallel was added. The option can be enabled in  Bigcommerce > Settings > Product Sync. Enabling it will add an additional background task runs on listings, channels initialization, and product data fetching.
- Added support for customer webhooks, which will enable real-time data syncing between BigCommerce and BC4WP for customer related data, such as new customers being created and updated login settings. The options can be enabled during onboarding process or in Bigcommerce > Settings > Product Sync

### Fixed
- Improve import process performance, optimize cleanup queries in order to reduce server resource consumption. Perform an additional cleanup before import starts.

### CODE REVIEW

**Review by amckemie — APPROVED** [review]

**Comment by amckemie** [comment]
cc: @bigcommerce/dev-docs

**Comment by bc-tgomez** [comment]
Will need to add this into the devdocs. Is there a ticket open for this @amckemie?

**Comment by amckemie** [comment]
@bc-tgomez no, that is not part of our current process. The approach was to ping y'all here and for y'all to take this info and update changelog / dev docs as needed.

**Comment by markcmurphy** [comment]
> @bc-tgomez no, that is not part of our current process. The approach was to ping y'all here and for y'all to take this info and update changelog / dev docs as needed.

@amckemie I will go over the changelog process with Tina, we haven't gotten there yet 👍

**Pull request merged**
