### PR TITLE
Sync all categories for MSF stores via API

### PR DESCRIPTION
**Pull request by ipokrovkiy**
feat: Sync all categories for MSF stores via API

- Removed the 250-category limit by paginating through all categories.
- Aggregate all categories into a single array.
- Log warnings and information for debugging.

Previously, syncing categories for MSF stores via API was limited to 250. This change ensures all categories are synced.

### CODE REVIEW

**Review by chanceaclark — COMMENTED** [review]
Hey @ipokrovkiy, sorry to take a while to get to this. Overall looks good, but could you provide some proof in your PR that it works correctly. A video of the import working should be fine.

**Comment by ipokrovkiy** [comment]
Hi @chanceaclark, [here](https://app.screencast.com/z3uRDvrcHmhWd?conversation=4NUss8UNIgk7CV4s7W9jIj) is the recording of normal processing, and then with updated code showing sync picking up all the category import (importing from category 251+) and a fresh category sync (0 categories in WP)

**Review by chanceaclark — APPROVED** [review]
Thanks @ipokrovkiy, looks good on my end!

**Comment by ipokrovkiy** [comment]
Thank you! @chanceaclark

**Comment by ipokrovkiy** [comment]
@chanceaclark Do you happen to know when the package will be updated in the WordPress composer repository? (We install BC4WP from Wordpress composer repository)

**Comment by chanceaclark** [comment]
@ipokrovkiy I can do it today.

**Comment by ipokrovkiy** [comment]
Hi Chancellor,

Is this all set, can I upgrade?

Thank you
Ilya

[https://ci3.googleusercontent.com/mail-sig/AIorK4yWue8n2gkuMbFWfu_PLQWbzOwfUWRdGa6qga2DhdpFkox0FVVWDADHaA52XLCmY7kc7bivgdI]
Ilya Pokrovskiy
BUSINESS ANALYST / TECH LEAD, Wasserman Digital
***@***.******@***.***>
WASSERMAN BOSTON
C: (781) 408-0597
Web<https://digital-design-and-technology.teamwass.com/>  |  Twitter<https://twitter.com/Wasserman>  |  Instagram<https://www.instagram.com/wasserman/>

STATEMENT OF CONFIDENTIALITY

This email message may contain confidential, proprietary and/or privileged information.  It is intended only for the use of the intended recipient(s).  If you have received it in error, please immediately advise the sender by reply email and then delete this email message.

**Comment by chanceaclark** [comment]
Hey @ipokrovkiy, yeah you should be all set. Fix went out in version 5.1.0.

**Pull request merged**
