### PR TITLE
Create CODEOWNERS and add dev-docs team

### PR DESCRIPTION
**Pull request by bookernath**
#### What?

Add a [CODEOWNERS file](https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/about-code-owners) and make sure @bigcommerce/dev-docs gets pinged on any changes to CHANGELOG.md (which should mostly be for new versions)

### CODE REVIEW

**Comment by PascalZajac** [comment]
Since packaging new releases appears to be done via hand and Pull Request, this will block those PRs from being merged until someone from the dev docs team approves them. Is that the intention?

**Comment by uwikaiddi** [comment]
@PascalZajac, the Dev Docs team does not need to be designated a code owner for this repo. Watching serves our purposes well enough. Thank you for checking.

**Comment by bookernath** [comment]
CODEOWNERS can also be used to only ping certain groups, but it turns out those groups also have to have write access to the repo or it won't work.

**Comment by amckemie** [comment]
@bookernath welp, I'm the worst at noticing PR reviews that I'm tagged in. Apologies. Based on the above convo, is this something we still want to pursue / add? It seems like no, but I wanted to check before closing.

**Review by traci707 — APPROVED** [review]

**Comment by uwikaiddi** [comment]
@bookernath @amckemie, please disregard the dev-docs request approval. Dev-docs does not need to be a CODEOWNER for this repo.

**Pull request closed without merging**
