### PR TITLE
adding proxy server endpoint to add cart item

### PR DESCRIPTION
**Pull request by AbdullahAdeeb**
#### What?

A description about what this pull request implements and its purpose. Try to be detailed and describe any technical details to simplify the job of the reviewer and the individual on production support.

#### Tickets / Documentation

Add links to any relevant tickets and documentation.

- [Link 1](http://example.com)
- ...

#### Screenshots (if appropriate)

Attach images or add image links here.

Example Image

### CODE REVIEW

**Comment by amckemie** [comment]
@AbdullahAdeeb Can you please fill out the actual information about what this PR is trying to solve, etc? This will help our team better review this PR. cc: @bc-ppuente

**Comment by bc-ppuente** [comment]
**What?**
Implements the [Create Cart Item](https://developer.bigcommerce.com/api-reference/store-management/carts/cart-items/addcartlineitem) endpoint in the REST proxy. Documentation indicates it currently exists: https://developer.bigcommerce.com/bigcommerce-for-wordpress/extending-the-plugin/proxy-rest-api-endpoints

This change enables WordPress to add multiple items to the cart with a single request. This change also allows developers writing JS to create carts with the [Create Cart](https://developer.bigcommerce.com/api-reference/storefront/carts/cart/createacart) endpoint in the REST proxy to use the same interface for adding additional items to the cart.

**Tickets / Documentation**
Proxy documentation: https://developer.bigcommerce.com/bigcommerce-for-wordpress/extending-the-plugin/proxy-rest-api-endpoints

**Comment by amckemie** [comment]
We are reviewing this and will have an engineer get back to you as soon as possible.

**Comment by amckemie** [comment]
Support for this was added on v4.7.0 of the plugin. Apologies for the delay in updating this

**Pull request closed without merging**
